### ISSUE TITLE
Autosave faillure 

### ISSUE THREAD

**Issue by HealHer** [Tylio5555/Dragon_Of_Doom#1]
Hi, 

I tried running dod.py to play Dragon of Doom. 
I got a **YAML warning** and the main menu. 
After trying `T` for Team Management the autosave crashes. 

```
Traceback (most recent call last):
  File "dod.py", line 733, in <module>
    game_world().main_town()
  File "dod.py", line 480, in main_town
    self.autosave()
  File "dod.py", line 402, in autosave
    self.save_world(self, autosave=True)
TypeError: save_world() got multiple values for argument 'autosave'
```

**Comment by Tylio5555** [comment]
As you can see :
File "dod.py", line 480, in main_town
    self.autosave()
self.autosave is missing the self arguments. 
This issue was fixed in this morning push. 
Pull the new version and also the import of prettytable was also rework with a "try ... except". if an import error persist with the launch of "main.py", directly use "scripts/dod.py"
